name: Redeploy Cloudflare Pages
on: repository_dispatch
jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Redeploy
        run: |
          git config --global user.email "+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git commit -m "CMS updated, redeploy" --allow-empty
          git push
